# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds: 
    - | 
      # fd -e png -x cp {} ./_site/
      cd src
      R -e "bookdown::render_book()" --slave --no-save > /dev/null
      cd ..
      cd book
      ./build_pdf > /dev/null
      osascript -e 'display notification "Finished building"'
    silent: true
